site_name: "mkdocs-shadcn"
site_url: "https://asiffer.github.io/mkdocs-shadcn"
site_description: "Documentation that also shines"
site_author: "Alban Siffer <31479857+asiffer@users.noreply.github.com>"
dev_addr: "127.0.0.1:8080"
repo_url: "https://github.com/asiffer/mkdocs-shadcn"
theme:
  name: shadcn
  icon: null
  topbar_sections: false
  carousel: true
  header_tabs:
    - label: Documentation
      icon: lucide:book-open
      url: .
    - label: Guides
      icon: lucide:compass
      url: guides/
      section: Guides
      match:
        - reference/
    - label: App Demo
      icon: lucide:braces
      url: app_demo/
  code_refs:
    endpoint:
      reference_page: app_demo/
      tags:
        /api/users: Users
        /api/items: Items
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    trust: true
    macros:
      "\\dx": "\\mathrm{d}x"
      "\\NN": "\\mathbb{N}"
  # show_datetime: true
  # accent: "oklch(64.5% 0.246 16.439)"

plugins:
  - search
  - excalidraw
  - mkdocstrings
  - autonumber:
      prefixes:
        th: Theorem

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
  shadcn.extensions.hover_card:
